services:
  api:
    build:
      context: .                      # repo root
      dockerfile: apps/api/Dockerfile.dev
    ports:
      - "5050:5050"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5050
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./apps/api:/app               # mount source for dotnet watch
      - /app/bin
      - /app/obj
    depends_on:
      - bitcoin

  web:
    image: node:20
    working_dir: /workspace
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5050
      HOSTNAME: 0.0.0.0
      CI: "true"
    volumes:
      - ./:/workspace
      - pnpm-store:/root/.local/share/pnpm/store
    command: >
      bash -lc "
        corepack enable &&
        corepack prepare pnpm@10.18.3 --activate &&
        pnpm install --no-frozen-lockfile &&
        pnpm approve-builds sharp unrs-resolver || true &&
        pnpm --filter web dev
      "
    depends_on:
      - api
      - bitcoin

  bitcoin:
    image: ruimarinho/bitcoin-core:latest
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_RPCUSER: heimdall
      BITCOIN_RPCPASSWORD: heimdall
      BITCOIN_RPCALLOWIP: 0.0.0.0/0
    command: >
      -printtoconsole
      -server=1
      -regtest=1
      -fallbackfee=0.0002
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcuser=heimdall
      -rpcpassword=heimdall
    ports:
      - "18443:18443"
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin

volumes:
  pnpm-store:
  bitcoin-data:
